import { createSlice } from "@reduxjs/toolkit";

const cartSlice = createSlice({
    name:"cart",
    initialState: {
        items:[]
    },
    reducers:{
        addItem: (state, action)=>{
            state.items.push(action.payload)
            // this doesn't returns anything, it just takes the state and modifies it. So, don't use return 
        },
        removeItem: (state, action)=>{
            state.items.pop();
        },
        clearCart: (state)=>{
            state.items=[]
        }
    }
});

export const {addItem, removeItem, clearCart} = cartSlice.actions;
//    This line exports the action creators generated by createSlice based on the names of the reducer functions defined earlier. These exported action creators can be used in components to dispatch the corresponding actions.
export default cartSlice.reducer;
//   this exports reducer function generated by createSclice, The reducer handles the state updates based on the actions dispatched.